In [2]:
from scipy import linalg
import numpy as np

In [3]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
B=np.array([1,2,3])
print(B)

[1 2 3]


In [5]:
x=linalg.solve(A,B)
print(x)

[-0.23333333  0.46666667  0.1       ]


C:\Users\86136\AppData\Local\Temp/ipykernel_1636/3412012307.py:1: LinAlgWarning: Ill-conditioned matrix (rcond=2.20282e-18): result may not be accurate.
  x=linalg.solve(A,B)


#  Check that your solution is correct by plugging it into the equation

In [6]:
np.dot(A,x)-B   #check

array([ 0.00000000e+00, -2.22044605e-16,  0.00000000e+00])

# Repeat steps a-d using a random 3x3 matrix B (instead of the vector b)


In [18]:
B1=np.random.rand(3,3)
A1=np.random.rand(3,3)
print(A1)
print(B1)


[[0.0687475  0.76125826 0.7538302 ]
 [0.16254837 0.56335836 0.23651802]
 [0.05539379 0.48734358 0.53118694]]
[[0.12684781 0.74191483 0.79019748]
 [0.18241329 0.35716567 0.03185026]
 [0.15528218 0.73784912 0.28760587]]


In [19]:
x1=linalg.solve(A1,B1)
print(x1)

[[  3.09379132   8.27218923 -10.67797772]
 [ -0.90457648  -3.21042625   3.97303024]
 [  0.79961471   3.47185082  -1.99013032]]


In [20]:
np.dot(A1,x1)-B1

array([[-2.77555756e-17, -2.22044605e-16, -1.11022302e-16],
       [-2.77555756e-17,  5.55111512e-17,  3.53883589e-16],
       [ 0.00000000e+00,  2.22044605e-16, -1.11022302e-16]])

# Solve the eigenvalue problem for the matrix A and print the eigenvalues and eigenvectors


In [21]:
Result=linalg.eig(A)
print(Result[0])  #eigenvalues
print(Result[1])  #eigenvectors

[ 1.61168440e+01+0.j -1.11684397e+00+0.j -3.38433605e-16+0.j]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


# Calculate the inverse, determinant of A

In [30]:
print(linalg.inv(A))
np.dot(A,linalg.inv(A))                         # A is a singular Matrix. The inverse of a singular matrix is not defined

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


array([[ 0. ,  1. , -0.5],
       [ 0. ,  2. , -1. ],
       [-4. ,  3. , -1.5]])

In [26]:
print(linalg.inv(A1))

np.dot(A1,linalg.inv(A1))    

[[-26.60250161   5.34935007  35.37088355]
 [ 10.59020755   0.75762496 -15.36636087]
 [ -6.94191808  -1.25293828  12.29203782]]


array([[ 1.00000000e+00,  1.43305335e-16,  1.05469912e-15],
       [ 1.98412724e-16,  1.00000000e+00, -1.72629760e-16],
       [-5.72507465e-16,  7.48387536e-17,  1.00000000e+00]])

In [27]:
linalg.det(A1)

-0.006916006150935883

In [28]:
linalg.det(A)    # A is a singular matrix

0.0

# Calculate the norm of A with different orders

In [32]:
linalg.norm(A,1)

18.0

In [33]:
linalg.norm(A,2)

16.84810335261421

In [34]:
linalg.norm(A,-2)

3.3347528650314325e-16